POST http://localhost:8080/employees HTTP/1.1
Content-Type: application/json

{
  "name":"Ripal Barot",
  "designation": "executive",
  "username": "ripplejb",
  "password": "strongPassword"
}

###

POST http://localhost:8080/employees HTTP/1.1
Content-Type: application/json

{
  "name":"Ripal Manager",
  "designation": "manager",
  "username": "ripple-manager",
  "password": "strongPassword"
}

###

POST http://localhost:8080/employees HTTP/1.1
Content-Type: application/json

{
  "name":"Ripal Creator",
  "designation": "creator",
  "username": "ripple-creator",
  "password": "strongPassword"
}

###

POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
  "username": "ripple-manager",
  "password": "strongPassword"
}

###

POST http://localhost:8080/departments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YTMxMThlZC00NTdmLTRhOGEtYTRkNS1iNGIyZWM3MzczODciLCJuYmYiOjE1OTM3NzQ1OTksImlzcyI6ImRvY3VtZW50LW1hbmFnZXIiLCJzY29wZXMiOlsiZXhlY3V0aXZlOmRvY3VtZW50LnJlYWRvbmx5IiwiZXhlY3V0aXZlOmRlcGFydG1lbnQuY3JlYXRlIl0sImRlc2lnbmF0aW9uIjoiZXhlY3V0aXZlIiwiZXhwIjoxNTkzNzc4MTk5LCJpYXQiOjE1OTM3NzQ1OTl9.m0Bgkqk-eD6dlRWeID7vdhZpQ9q_kxkxw0UMmodMagk

{
  "name": "Finance",
  "managerId": "779e6a1c-8cac-4bf3-8c44-62575cca1750"
}

###

POST http://localhost:8080/documents HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMTcxODg2Zi05MGE0LTRhYzAtYWRhMS1jZmU5MGExMTgzZGIiLCJuYmYiOjE1OTM3NzQ5MjIsImlzcyI6ImRvY3VtZW50LW1hbmFnZXIiLCJzY29wZXMiOlsibWFuYWdlcjpkb2N1bWVudC5yZWFkb25seSIsIm1hbmFnZXI6ZG9jdW1lbnQudXBkYXRlIl0sImRlc2lnbmF0aW9uIjoibWFuYWdlciIsImV4cCI6MTU5Mzc3ODUyMiwiaWF0IjoxNTkzNzc0OTIyfQ.G1IngOCD5CY6jKbE5ualqrMa8gmJONrIMxN3-iT_w90

{
  "creatorId": "8a3118ed-457f-4a8a-a4d5-b4b2ec737387",
  "departmentId": "2171886f-90a4-4ac0-ada1-cfe90a1183db",
  "title": "My Title",
  "content": "My Content"
}